spring.application.name=token-vault
server.port=8080

# H2 Database settings
spring.datasource.url=jdbc:h2:mem:tokenvaultdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Allow frame options so H2 console can render in an iframe
spring.headers.frame-options=sameorigin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
